# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
language: scala
scala:
  - 2.10.6
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/67562f0726ed2388330c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false
# Use container-based infrastructure
sudo: false
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
